name: "UTBot Java: build and run tests"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_run_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
        java-package: jdk+fx
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.8
        
    - name: Build and run tests in UTBot Java
      run: |
        export KOTLIN_HOME="/usr"
        gradle clean build --no-daemon
